config/routes.rb
Rails.application.routes.draw do

  root 'medicare_payments#index'

  resources :medicare_payments
end

app/models/medicare_payment.rb
class MedicarePayment < ActiveRecord::Base
  acts_as_copy_target

  searchable do
    text :npi, :provider_last_org_name, :provider_first_name, :hcpcs_code, :hcpcs_description
    string :provider_state
    string :provider_gender
    string :provider_type
    string :provider_credentials
    integer :line_srvc_cnt
    integer :average_medicare_payment_amt
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/medicare_payments_controller.rb
class MedicarePaymentsController < ApplicationController

  def index
    @search = MedicarePayment.search do
      fulltext params[:search]
      facet(:provider_state, :provider_gender, :provider_type, :provider_credentials)
      with(:provider_state, params[:provider_state]) if params[:provider_state]
      with(:provider_gender, params[:provider_gender]) if params[:provider_gender]
      with(:provider_type, params[:provider_type]) if params[:provider_type]
      with(:provider_credentials, params[:provider_credentials]) if params[:provider_credentials]
      paginate(page: params[:page])
    end

    @medicare_payments = @search.results
    @filter = params[:filter] ||= { "None" => "" }
  end

  def show
    @medicare_payment = MedicarePayment.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Medicare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/medicare_payments/_filters_sidebar.html.erb
<h4>Filters</h4>
<ul class="nav nav-sidebar">
  <%= render 'filters_sidebar_by_state' %>
  <%= render 'filters_sidebar_by_gender' %>
  <%= render 'filters_sidebar_by_type' %>
  <%= render 'filters_sidebar_by_credentials' %>
</ul>

app/views/medicare_payments/_filters_sidebar_by_credentials.html.erb
<li class="nav-header">
  By Provider Credentials
</li>
<% for row in @search.facet(:provider_credentials).rows.first(5) %>
  <li>
    <% if params[:provider_credentials].blank? %>
    <h6>
      <%= link_to row.value, medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_gender => params[:provider_gender], :provider_type => params[:provider_type], :provider_credentials => row.value) %>
      <span class="pull-right"><%= number_with_precision(row.count, :precision => 0, :delimiter => ",") %></span>
    </h6>
    <% else %>
      <h6>
      <strong><%= row.value %></strong> (<%= link_to "remove", medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_gender => params[:provider_gender], :provider_type => params[:provider_type], :provider_credentials => nil) %>)
      </h6>
    <% end %>
  </li>
<% end %>

app/views/medicare_payments/_filters_sidebar_by_gender.html.erb
<li class="nav-header">
  By Gender
</li>
<% for row in @search.facet(:provider_gender).rows %>
  <li>
    <% if params[:provider_gender].blank? %>
    <h6>
      <%= link_to row.value, medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_type => params[:provider_type], :provider_gender => row.value) %>
      <span class="pull-right"><%= number_with_precision(row.count, :precision => 0, :delimiter => ",") %></span>
    </h6>
    <% else %>
      <h6>
      <strong><%= row.value %></strong> (<%= link_to "remove", medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_type => params[:provider_type], :provider_credentials => params[:provider_credentials], :provider_gender => nil) %>)
      </h6>
    <% end %>
  </li>
<% end %>

app/views/medicare_payments/_filters_sidebar_by_state.html.erb
<li class="nav-header">
  By State
</li>
<% for row in @search.facet(:provider_state).rows.first(5) %>
  <li>
    <% if params[:provider_state].blank? %>
    <h6>
      <%= link_to row.value, medicare_payments_path(:search => params[:search], :provider_gender => params[:provider_gender], :provider_type => params[:provider_type], :provider_state => row.value) %>
      <span class="pull-right"><%= number_with_precision(row.count, :precision => 0, :delimiter => ",") %></span>
    </h6>
    <% else %>
      <h6>
      <strong><%= row.value %></strong> (<%= link_to "remove", medicare_payments_path(:search => params[:search], :provider_gender => params[:provider_gender], :provider_type => params[:provider_type], :provider_credentials => params[:provider_credentials], :provider_state => nil) %>)
      </h6>
    <% end %>
  </li>
<% end %>

app/views/medicare_payments/_filters_sidebar_by_type.html.erb
<li class="nav-header">
  By Provider Type
</li>
<% for row in @search.facet(:provider_type).rows.first(5) %>
  <li>
    <% if params[:provider_type].blank? %>
    <h6>
      <%= link_to row.value, medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_gender => params[:provider_gender], :provider_type => row.value) %>
      <span class="pull-right"><%= number_with_precision(row.count, :precision => 0, :delimiter => ",") %></span>
    </h6>
    <% else %>
      <h6>
      <strong><%= row.value %></strong> (<%= link_to "remove", medicare_payments_path(:search => params[:search], :provider_state => params[:provider_state], :provider_gender => params[:provider_gender], :provider_credentials => params[:provider_credentials], :provider_type => nil) %>)
      </h6>
    <% end %>
  </li>
<% end %>

app/views/medicare_payments/index.html.erb
<%= form_tag medicare_payments_path, method: :get, :class => "navbar-form pull right", id: "medicare_payments_search" do %>
<div class="row searchheader">
  <div class="col-md-6">
    <h1>Medicare Payment Data <small>2013</small></h1>
  </div>
  <div class="col-md-2 col-md-offset-3 search-query">
    <%= text_field_tag :search, params[:search], { :placeholder => "Search",:class=>"search-query" } %>
  </div>
  <div class="col-md-1">
    <button type="submit" class="btn btn-primary" value="search">Search</button>
  </div>
</div>
<% end %>

<div class="row">
  <div class="col-md-2 sidebar">
    <%= render 'filters_sidebar' %>
  </div>
  <div class="col-md-10">
    <table class="table table-striped table-condensed table-responsive">
      <tr>
        <th>Last / Org Name</th>
        <th>First Name</th>
        <th>M.I.</th>
        <th>Credentials</th>
        <th>Gender</th>
        <th>City</th>
        <th>State</th>
        <th>Provider Type</th>
        <th>HCPCS Code</th>
        <th>HCPCS Description</th>
        <th># of Services</th>
        <th>Avg Medicare Pmt Amt</th>
      </tr>

      <% @medicare_payments.each do |medicare_payment| %>
        <tr>
          <td nowrap><%= medicare_payment.provider_last_org_name %></td>
          <td nowrap><%= medicare_payment.provider_first_name %></td>
          <td nowrap><%= medicare_payment.provider_mi %></td>
          <td nowrap><%= medicare_payment.provider_credentials %></td>
          <td nowrap><%= medicare_payment.provider_gender %></td>
          <td nowrap><%= medicare_payment.provider_city %></td>
          <td nowrap><%= medicare_payment.provider_state %></td>
          <td><%= medicare_payment.provider_type %></td>
          <td nowrap><%= medicare_payment.hcpcs_code %></td>
          <td><%= medicare_payment.hcpcs_description %></td>
          <td nowrap><%= medicare_payment.line_srvc_cnt %></td>
          <td nowrap><%= medicare_payment.average_medicare_payment_amt %></td>
        </tr>
      <% end %>
      
    </table>

    <%= will_paginate @medicare_payments, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/medicare_payments/show.html.erb
<table>
  <tr>
    <th>Attribute</th>
    <th>Value</th>
  </tr>
      
  <% @medicare_payment.attributes.each do |attribute, value| %>
    <tr>
      <td><%= attribute %></td>
      <td><%= value %></td>
    </tr>
  <% end %>
</table>